# Generated by Django 5.1.5 on 2025-04-05 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='photo',
            field=models.ImageField(default=1, upload_to='trainers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='quote',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
